// <auto-generated />
using System;
using HbDotnetFileOrchestrator.Infrastructure.Sql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HbDotnetFileOrchestrator.Infrastructure.Sql.Migrations
{
    [DbContext(typeof(StorageDbContext))]
    partial class StorageDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("StorageBaseDboSequence");

            modelBuilder.Entity("HbDotnetFileOrchestrator.Infrastructure.Sql.Models.StorageAuditDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("StorageAudit", (string)null);
                });

            modelBuilder.Entity("HbDotnetFileOrchestrator.Infrastructure.Sql.Models.StorageBaseDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR [StorageBaseDboSequence]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("RuleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("RuleId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("HbDotnetFileOrchestrator.Infrastructure.Sql.Models.StorageRuleDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Expression")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("StorageRule", (string)null);
                });

            modelBuilder.Entity("HbDotnetFileOrchestrator.Infrastructure.Sql.Models.FileSystemStorageDbo", b =>
                {
                    b.HasBaseType("HbDotnetFileOrchestrator.Infrastructure.Sql.Models.StorageBaseDbo");

                    b.ToTable("FileSystemStorage", (string)null);
                });

            modelBuilder.Entity("HbDotnetFileOrchestrator.Infrastructure.Sql.Models.StorageAuditDbo", b =>
                {
                    b.OwnsOne("System.Collections.Generic.Dictionary<string, object>", "Properties", b1 =>
                        {
                            b1.Property<int>("StorageAuditDboId");

                            b1.HasKey("StorageAuditDboId");

                            b1.ToTable("StorageAudit");

                            b1.ToJson("Properties");

                            b1.WithOwner()
                                .HasForeignKey("StorageAuditDboId");
                        });

                    b.Navigation("Properties")
                        .IsRequired();
                });

            modelBuilder.Entity("HbDotnetFileOrchestrator.Infrastructure.Sql.Models.StorageBaseDbo", b =>
                {
                    b.HasOne("HbDotnetFileOrchestrator.Infrastructure.Sql.Models.StorageRuleDbo", "StorageRuleDbo")
                        .WithMany("Storages")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StorageRuleDbo");
                });

            modelBuilder.Entity("HbDotnetFileOrchestrator.Infrastructure.Sql.Models.StorageRuleDbo", b =>
                {
                    b.Navigation("Storages");
                });
#pragma warning restore 612, 618
        }
    }
}
